// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYgL5skZKuRrFSm5Bl7aJkPcR23bSU-Co',
    appId: '1:128236941532:web:efc722622df2e07fcac419',
    messagingSenderId: '128236941532',
    projectId: 'makeupflow-50f68',
    authDomain: 'makeupflow-50f68.firebaseapp.com',
    storageBucket: 'makeupflow-50f68.firebasestorage.app',
    measurementId: 'G-SYRD9C2NQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEM2-xyPPtKZJRVl2hx4aUh9BspWQo31E',
    appId: '1:128236941532:android:1338324b4e09fee8cac419',
    messagingSenderId: '128236941532',
    projectId: 'makeupflow-50f68',
    storageBucket: 'makeupflow-50f68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ17CbW-dB1PJv0PehOfDcKxt8C9pYoc8',
    appId: '1:128236941532:ios:ee31ccc65e370204cac419',
    messagingSenderId: '128236941532',
    projectId: 'makeupflow-50f68',
    storageBucket: 'makeupflow-50f68.firebasestorage.app',
    iosBundleId: 'com.example.makeupflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ17CbW-dB1PJv0PehOfDcKxt8C9pYoc8',
    appId: '1:128236941532:ios:ee31ccc65e370204cac419',
    messagingSenderId: '128236941532',
    projectId: 'makeupflow-50f68',
    storageBucket: 'makeupflow-50f68.firebasestorage.app',
    iosBundleId: 'com.example.makeupflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYgL5skZKuRrFSm5Bl7aJkPcR23bSU-Co',
    appId: '1:128236941532:web:b34d10f9c7adbc6dcac419',
    messagingSenderId: '128236941532',
    projectId: 'makeupflow-50f68',
    authDomain: 'makeupflow-50f68.firebaseapp.com',
    storageBucket: 'makeupflow-50f68.firebasestorage.app',
    measurementId: 'G-CBQNHFJEEZ',
  );
}
